name: Code formatting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install Black
      run: pip install black[jupyter]==22.3
    - name: Run Black
      run: black --config=black.toml --check .
