name: Code formatting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  format:
    name: Black formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install Black
      run: pip install black[jupyter]==22.3
    - name: Run Black
      run: black --config=black.toml --check .

  lint:
    name: Flake8 linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install linters
      run: pip install flake8==4.0.1 flake8-docstrings==1.6.0
    - name: Run Flake8
      run: flake8
